Append data into DB using shell of Django ORM
thinknetica-django-lab-05/Denmikola pull request #39
Opened 2021-11-15 07:37 UTC by Denmikola

Closes #7

2021-11-15 07:39 UTC, Denmikola commented
Единственное что я не придумал как выводить человеческое имя столбца для num_ads в админке

2021-11-18 06:55 UTC, ilyuhi4 commented on Deimos/main/models.py
> +    slug = models.SlugField(blank=True)
будет ли в такой конфигурации корректно создаваться слаг? и почему от может быть blank?

2021-11-18 06:55 UTC, ilyuhi4 commented on Deimos/main/models.py
> +    slug = models.SlugField(blank=True)
а что с кириллическими символами?

2021-11-18 06:57 UTC, ilyuhi4 commented on Deimos/main/models.py
>                                  .format(title=self.title, rands=get_random_string()))
вот так вот просто рандомная строчка?
может быть стандартные методы позволяют получить что-то поинтереснее?

2021-11-18 06:58 UTC, ilyuhi4 commented on Deimos/main/tests.py
> +
ой ой ой
а отчего не воспользовался циклами?
В задании: "При создании объявлений испльзовать методы save() и create()"
Create увидел Save не увидел: какая между ними разница?

2021-11-18 06:58 UTC, ilyuhi4 commented on Deimos/main/tests.py
> +
так же не увидел результатов вывода

2021-11-18 06:59 UTC, ilyuhi4 requested changes
Нужно немного доработать

2021-11-18 07:08 UTC, Denmikola commented on Deimos/main/models.py
>                                  .format(title=self.title, rands=get_random_string()))
ммм, не очень понимаю к чему клонишь. когда я добавил эту строку впервые вроде бы вопросов не возникло.

2021-11-18 07:08 UTC, Denmikola commented on Deimos/main/tests.py
> +
циклами нет потому что добавляемые значения немного уникальны, ну и не было задания)

2021-11-18 07:11 UTC, Denmikola commented on Deimos/main/tests.py
> +
строка с одним save есть, разницу я понимаю - что сперва создается обьект класса, модифицируется и по save сохраняется в БД, а по create и создание обьекта и сохранение в БД одновременно происходит

2021-11-18 07:12 UTC, Denmikola commented on Deimos/main/tests.py
> +
если нужны результаты вывода - могу добавить

2021-11-20 09:13 UTC, ilyuhi4 approved these changes

2021-11-20 09:13 UTC, ilyuhi4 commented
Сливай ветки и полетели дальше!

2021-11-21 11:29 UTC, merged