3 2 create header footer
thinknetica-django-lab-05/Denmikola pull request #58
Opened 2021-11-23 16:10 UTC by Denmikola

closes #14

2021-11-27 08:12 UTC, ilyuhi4 commented on Deimos/main/models.py
> +            self.slug = slugify("{name}-{rands}".format(name=self.name, rands=get_random_string()))
зачем использовать random? slugify отлично справляется даже с кирилицей

2021-11-27 08:14 UTC, ilyuhi4 commented on Deimos/main/models.py
> +    objects = LiveAdsManager()
эта штука тут зачем нужна?

2021-11-27 08:15 UTC, ilyuhi4 commented on Deimos/main/models.py
> +        return super().get_queryset().filter(archived=False)
я бы не стал здесь так делать - нам в пределе нужны все объявления в кверисете

2021-11-27 08:15 UTC, ilyuhi4 commented on Deimos/main/views.py
> +    return render(request, 'main/index.html', {'turn_on_block': config.MAINTENANCE_MODE})
может перепишем в CBV?

2021-11-27 08:16 UTC, ilyuhi4 requested changes
необходимо немного доработать

2021-11-27 15:40 UTC, Denmikola commented on Deimos/main/models.py
> +            self.slug = slugify("{name}-{rands}".format(name=self.name, rands=get_random_string()))
так было в примере когда добавляли это поле, я подумал что может потом пригодится

2021-11-27 15:45 UTC, Denmikola commented on Deimos/main/models.py
> +    objects = LiveAdsManager()
если про LiveAdsManager(), то я сделал чтобы не видно было архивных обьявлений в основном интерфейсе

2021-11-27 15:46 UTC, Denmikola commented on Deimos/main/models.py
> +        return super().get_queryset().filter(archived=False)
уберу значит

2021-11-27 15:59 UTC, Denmikola commented on Deimos/main/views.py
> +    return render(request, 'main/index.html', {'turn_on_block': config.MAINTENANCE_MODE})
не понимаю как это здесь реализуемо ((
да и в задании было сказано:
"В обработчике index в шаблон передаётся переменная turn_on_block, её значение берётся из MAINTENANCE_MODE"
в доке так же сделано https://django-constance.readthedocs.io/en/latest/#django-templates

2021-11-30 06:58 UTC, ilyuhi4 commented on Deimos/main/views.py
> +    return render(request, 'main/index.html', {'turn_on_block': config.MAINTENANCE_MODE})
окей. оставляй так. дальше разберемся :)
Вообще можно просто сделать предствление класс наследованный от TemplateView и передать ему extra_context

2021-11-30 06:59 UTC, ilyuhi4 approved these changes

2021-11-30 07:55 UTC, merged